'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Volume2, VolumeX, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { HomeBackdropSheet } from '@/components/home-backdrop-sheet';
const pages = ['Copertina Front-clean.jpg','Pag.1-clean.jpg','Pag 2-clean.jpg','Pag.3-clean.jpg'];
export default function TracceMagazinePage() {
 const [spread,setSpread]=useState(0); const [direction,setDirection]=useState<'next'|'previous'>('next'); const [open,setOpen]=useState(false); const [muted,setMuted]=useState(true); const count=Math.ceil(pages.length/2);
 const move=(step:1|-1)=>{setDirection(step===1?'next':'previous');setSpread(v=>Math.max(0,Math.min(count-1,v+step)));};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!open)return;if(e.key==='Escape')setOpen(false);if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open]);
 const left=pages[spread*2],right=pages[spread*2+1];
 return <main className="portfolio-stage magazine-page-stage"><section className="vinyl-table magazine-table" aria-label="Tracce Magazine"><HomeBackdropSheet/><img className="desk-background" src="/art/desk-photo.jpg" alt=""/>{!open?<button className="magazine-cover-card" onClick={()=>setOpen(true)} aria-label="Apri Tracce Magazine"><img src={`/art/tracce/${pages[0]}`} alt="Copertina di Tracce Magazine"/></button>:<div className={`magazine-reader magazine-reader-${direction}`}><Button className="vinyl-back-button" variant="outline" size="icon-lg" onClick={()=>setOpen(false)} aria-label="Chiudi magazine"><X/></Button><Button className="magazine-sound" variant="outline" size="icon-lg" onClick={()=>setMuted(v=>!v)} aria-label="Attiva o disattiva suono">{muted?<VolumeX/>:<Volume2/>}</Button><Button className="vinyl-nav vinyl-nav-previous" variant="outline" size="icon-lg" onClick={()=>move(-1)} disabled={!spread} aria-label="Doppia pagina precedente"><ArrowLeft/></Button><div className="magazine-spread" key={spread}><div className="magazine-page"><img src={`/art/tracce/${left}`} alt={`Pagina ${spread*2+1}`}/></div>{right?<div className="magazine-page"><img src={`/art/tracce/${right}`} alt={`Pagina ${spread*2+2}`}/></div>:<div className="magazine-page magazine-blank"/>}</div><Button className="vinyl-nav vinyl-nav-next" variant="outline" size="icon-lg" onClick={()=>move(1)} disabled={spread===count-1} aria-label="Doppia pagina successiva"><ArrowRight/></Button><div className="vinyl-detail-meta"><span>{spread*2+1}–{Math.min(spread*2+2,pages.length)} / {pages.length}</span><h1>Tracce Magazine</h1><button className="vinyl-return-link" onClick={()=>setOpen(false)}>Torna alla copertina</button></div></div>}</section></main>;
}
